import { NewsResponse } from "@lib/types";

export const MOCK_WEATHER_RESPONSE = {
    type: "FeatureCollection",
    features: [
        {
            type: "Feature",
            geometry: { type: "Point", coordinates: [-2.4996, 51.8249, 186] },
            properties: {
                location: { name: "Cinderford" },
                requestPointDistance: 52.2513,
                modelRunDate: "2022-08-03T22:00Z",
                timeSeries: [
                    {
                        time: "2022-08-02T00:00Z",
                        midnight10MWindSpeed: 6.22,
                        midnight10MWindDirection: 229,
                        midnight10MWindGust: 12.86,
                        midnightVisibility: 14734,
                        midnightRelativeHumidity: 89.55,
                        midnightMslp: 101240,
                        nightSignificantWeatherCode: 7,
                        nightMinScreenTemperature: 17.76,
                        nightUpperBoundMinTemp: 18.26,
                        nightLowerBoundMinTemp: 16.26,
                        nightMinFeelsLikeTemp: 16.58,
                        nightUpperBoundMinFeelsLikeTemp: 16.58,
                        nightLowerBoundMinFeelsLikeTemp: 14.69,
                        nightProbabilityOfPrecipitation: 10,
                        nightProbabilityOfSnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        nightProbabilityOfRain: 10,
                        nightProbabilityOfHeavyRain: 2,
                        nightProbabilityOfHail: 0,
                        nightProbabilityOfSferics: 0,
                    },
                    {
                        time: "2022-08-03T00:00Z",
                        midday10MWindSpeed: 6.07,
                        midnight10MWindSpeed: 2.8,
                        midday10MWindDirection: 236,
                        midnight10MWindDirection: 271,
                        midday10MWindGust: 9.77,
                        midnight10MWindGust: 8.08,
                        middayVisibility: 22594,
                        midnightVisibility: 25202,
                        middayRelativeHumidity: 72.83,
                        midnightRelativeHumidity: 80.61,
                        middayMslp: 101280,
                        midnightMslp: 101380,
                        maxUvIndex: 1,
                        daySignificantWeatherCode: 7,
                        nightSignificantWeatherCode: 0,
                        dayMaxScreenTemperature: 22.9,
                        nightMinScreenTemperature: 13.24,
                        dayUpperBoundMaxTemp: 23.94,
                        nightUpperBoundMinTemp: 14.01,
                        dayLowerBoundMaxTemp: 21,
                        nightLowerBoundMinTemp: 11,
                        dayMaxFeelsLikeTemp: 20.47,
                        nightMinFeelsLikeTemp: 12.65,
                        dayUpperBoundMaxFeelsLikeTemp: 20.94,
                        nightUpperBoundMinFeelsLikeTemp: 13.04,
                        dayLowerBoundMaxFeelsLikeTemp: 18.19,
                        nightLowerBoundMinFeelsLikeTemp: 10.14,
                        dayProbabilityOfPrecipitation: 3,
                        nightProbabilityOfPrecipitation: 0,
                        dayProbabilityOfSnow: 0,
                        nightProbabilityOfSnow: 0,
                        dayProbabilityOfHeavySnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        dayProbabilityOfRain: 3,
                        nightProbabilityOfRain: 0,
                        dayProbabilityOfHeavyRain: 0,
                        nightProbabilityOfHeavyRain: 0,
                        dayProbabilityOfHail: 0,
                        nightProbabilityOfHail: 0,
                        dayProbabilityOfSferics: 0,
                        nightProbabilityOfSferics: 0,
                    },
                    {
                        time: "2022-08-04T00:00Z",
                        midday10MWindSpeed: 3.75,
                        midnight10MWindSpeed: 3.59,
                        midday10MWindDirection: 313,
                        midnight10MWindDirection: 329,
                        midday10MWindGust: 6.96,
                        midnight10MWindGust: 7.78,
                        middayVisibility: 43902,
                        midnightVisibility: 35064,
                        middayRelativeHumidity: 39.24,
                        midnightRelativeHumidity: 63.57,
                        middayMslp: 101690,
                        midnightMslp: 102128,
                        maxUvIndex: 6,
                        daySignificantWeatherCode: 7,
                        nightSignificantWeatherCode: 0,
                        dayMaxScreenTemperature: 21.12,
                        nightMinScreenTemperature: 10.26,
                        dayUpperBoundMaxTemp: 21.91,
                        nightUpperBoundMinTemp: 11,
                        dayLowerBoundMaxTemp: 18.77,
                        nightLowerBoundMinTemp: 7.02,
                        dayMaxFeelsLikeTemp: 18.06,
                        nightMinFeelsLikeTemp: 8.79,
                        dayUpperBoundMaxFeelsLikeTemp: 19.28,
                        nightUpperBoundMinFeelsLikeTemp: 9.2,
                        dayLowerBoundMaxFeelsLikeTemp: 16.57,
                        nightLowerBoundMinFeelsLikeTemp: 7.53,
                        dayProbabilityOfPrecipitation: 4,
                        nightProbabilityOfPrecipitation: 0,
                        dayProbabilityOfSnow: 0,
                        nightProbabilityOfSnow: 0,
                        dayProbabilityOfHeavySnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        dayProbabilityOfRain: 4,
                        nightProbabilityOfRain: 0,
                        dayProbabilityOfHeavyRain: 0,
                        nightProbabilityOfHeavyRain: 0,
                        dayProbabilityOfHail: 0,
                        nightProbabilityOfHail: 0,
                        dayProbabilityOfSferics: 0,
                        nightProbabilityOfSferics: 0,
                    },
                    {
                        time: "2022-08-05T00:00Z",
                        midday10MWindSpeed: 4.51,
                        midnight10MWindSpeed: 2.67,
                        midday10MWindDirection: 321,
                        midnight10MWindDirection: 341,
                        midday10MWindGust: 8.68,
                        midnight10MWindGust: 5.33,
                        middayVisibility: 43477,
                        midnightVisibility: 31823,
                        middayRelativeHumidity: 38.44,
                        midnightRelativeHumidity: 75.94,
                        middayMslp: 102427,
                        midnightMslp: 102864,
                        maxUvIndex: 6,
                        daySignificantWeatherCode: 3,
                        nightSignificantWeatherCode: 0,
                        dayMaxScreenTemperature: 19.66,
                        nightMinScreenTemperature: 7.62,
                        dayUpperBoundMaxTemp: 21.21,
                        nightUpperBoundMinTemp: 10.17,
                        dayLowerBoundMaxTemp: 18.1,
                        nightLowerBoundMinTemp: 4.82,
                        dayMaxFeelsLikeTemp: 16.21,
                        nightMinFeelsLikeTemp: 7.42,
                        dayUpperBoundMaxFeelsLikeTemp: 18.67,
                        nightUpperBoundMinFeelsLikeTemp: 9.07,
                        dayLowerBoundMaxFeelsLikeTemp: 16.1,
                        nightLowerBoundMinFeelsLikeTemp: 2.32,
                        dayProbabilityOfPrecipitation: 4,
                        nightProbabilityOfPrecipitation: 0,
                        dayProbabilityOfSnow: 0,
                        nightProbabilityOfSnow: 0,
                        dayProbabilityOfHeavySnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        dayProbabilityOfRain: 4,
                        nightProbabilityOfRain: 0,
                        dayProbabilityOfHeavyRain: 0,
                        nightProbabilityOfHeavyRain: 0,
                        dayProbabilityOfHail: 0,
                        nightProbabilityOfHail: 0,
                        dayProbabilityOfSferics: 0,
                        nightProbabilityOfSferics: 0,
                    },
                    {
                        time: "2022-08-06T00:00Z",
                        midday10MWindSpeed: 2.3,
                        midnight10MWindSpeed: 3.03,
                        midday10MWindDirection: 359,
                        midnight10MWindDirection: 359,
                        midday10MWindGust: 6.38,
                        midnight10MWindGust: 5.34,
                        middayVisibility: 35834,
                        midnightVisibility: 31577,
                        middayRelativeHumidity: 41.87,
                        midnightRelativeHumidity: 73.84,
                        middayMslp: 102992,
                        midnightMslp: 102932,
                        maxUvIndex: 6,
                        daySignificantWeatherCode: 3,
                        nightSignificantWeatherCode: 0,
                        dayMaxScreenTemperature: 20.4,
                        nightMinScreenTemperature: 9.55,
                        dayUpperBoundMaxTemp: 21.42,
                        nightUpperBoundMinTemp: 11.52,
                        dayLowerBoundMaxTemp: 18.26,
                        nightLowerBoundMinTemp: 6.5,
                        dayMaxFeelsLikeTemp: 18.54,
                        nightMinFeelsLikeTemp: 9.36,
                        dayUpperBoundMaxFeelsLikeTemp: 19.79,
                        nightUpperBoundMinFeelsLikeTemp: 9.39,
                        dayLowerBoundMaxFeelsLikeTemp: 16.68,
                        nightLowerBoundMinFeelsLikeTemp: 5.17,
                        dayProbabilityOfPrecipitation: 4,
                        nightProbabilityOfPrecipitation: 1,
                        dayProbabilityOfSnow: 0,
                        nightProbabilityOfSnow: 0,
                        dayProbabilityOfHeavySnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        dayProbabilityOfRain: 4,
                        nightProbabilityOfRain: 1,
                        dayProbabilityOfHeavyRain: 0,
                        nightProbabilityOfHeavyRain: 0,
                        dayProbabilityOfHail: 0,
                        nightProbabilityOfHail: 0,
                        dayProbabilityOfSferics: 0,
                        nightProbabilityOfSferics: 0,
                    },
                    {
                        time: "2022-08-07T00:00Z",
                        midday10MWindSpeed: 1.83,
                        midnight10MWindSpeed: 3.54,
                        midday10MWindDirection: 22,
                        midnight10MWindDirection: 12,
                        midday10MWindGust: 6.1,
                        midnight10MWindGust: 5.97,
                        middayVisibility: 32831,
                        midnightVisibility: 31256,
                        middayRelativeHumidity: 44.58,
                        midnightRelativeHumidity: 74.66,
                        middayMslp: 102831,
                        midnightMslp: 102702,
                        maxUvIndex: 7,
                        daySignificantWeatherCode: 3,
                        nightSignificantWeatherCode: 0,
                        dayMaxScreenTemperature: 22.64,
                        nightMinScreenTemperature: 10.59,
                        dayUpperBoundMaxTemp: 24.06,
                        nightUpperBoundMinTemp: 11.96,
                        dayLowerBoundMaxTemp: 20.51,
                        nightLowerBoundMinTemp: 7.97,
                        dayMaxFeelsLikeTemp: 20.96,
                        nightMinFeelsLikeTemp: 10.57,
                        dayUpperBoundMaxFeelsLikeTemp: 23.15,
                        nightUpperBoundMinFeelsLikeTemp: 11.16,
                        dayLowerBoundMaxFeelsLikeTemp: 18.95,
                        nightLowerBoundMinFeelsLikeTemp: 6.27,
                        dayProbabilityOfPrecipitation: 3,
                        nightProbabilityOfPrecipitation: 0,
                        dayProbabilityOfSnow: 0,
                        nightProbabilityOfSnow: 0,
                        dayProbabilityOfHeavySnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        dayProbabilityOfRain: 3,
                        nightProbabilityOfRain: 0,
                        dayProbabilityOfHeavyRain: 0,
                        nightProbabilityOfHeavyRain: 0,
                        dayProbabilityOfHail: 0,
                        nightProbabilityOfHail: 0,
                        dayProbabilityOfSferics: 0,
                        nightProbabilityOfSferics: 0,
                    },
                    {
                        time: "2022-08-08T00:00Z",
                        midday10MWindSpeed: 2.22,
                        midnight10MWindSpeed: 3.76,
                        midday10MWindDirection: 107,
                        midnight10MWindDirection: 24,
                        midday10MWindGust: 6.91,
                        midnight10MWindGust: 6.05,
                        middayVisibility: 34903,
                        midnightVisibility: 30652,
                        middayRelativeHumidity: 42.62,
                        midnightRelativeHumidity: 72.11,
                        middayMslp: 102612,
                        midnightMslp: 102552,
                        maxUvIndex: 7,
                        daySignificantWeatherCode: 1,
                        nightSignificantWeatherCode: 0,
                        dayMaxScreenTemperature: 24.63,
                        nightMinScreenTemperature: 11.61,
                        dayUpperBoundMaxTemp: 26.72,
                        nightUpperBoundMinTemp: 13.46,
                        dayLowerBoundMaxTemp: 22.61,
                        nightLowerBoundMinTemp: 8.6,
                        dayMaxFeelsLikeTemp: 23.38,
                        nightMinFeelsLikeTemp: 11.77,
                        dayUpperBoundMaxFeelsLikeTemp: 25.25,
                        nightUpperBoundMinFeelsLikeTemp: 11.89,
                        dayLowerBoundMaxFeelsLikeTemp: 20.55,
                        nightLowerBoundMinFeelsLikeTemp: 7.93,
                        dayProbabilityOfPrecipitation: 0,
                        nightProbabilityOfPrecipitation: 0,
                        dayProbabilityOfSnow: 0,
                        nightProbabilityOfSnow: 0,
                        dayProbabilityOfHeavySnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        dayProbabilityOfRain: 0,
                        nightProbabilityOfRain: 0,
                        dayProbabilityOfHeavyRain: 0,
                        nightProbabilityOfHeavyRain: 0,
                        dayProbabilityOfHail: 0,
                        nightProbabilityOfHail: 0,
                        dayProbabilityOfSferics: 0,
                        nightProbabilityOfSferics: 0,
                    },
                    {
                        time: "2022-08-09T00:00Z",
                        midday10MWindSpeed: 2.37,
                        midnight10MWindSpeed: 3.44,
                        midday10MWindDirection: 130,
                        midnight10MWindDirection: 37,
                        midday10MWindGust: 6.96,
                        midnight10MWindGust: 5.47,
                        middayVisibility: 34489,
                        midnightVisibility: 29094,
                        middayRelativeHumidity: 42.39,
                        midnightRelativeHumidity: 77.72,
                        middayMslp: 102484,
                        midnightMslp: 102356,
                        maxUvIndex: 6,
                        daySignificantWeatherCode: 1,
                        nightSignificantWeatherCode: 0,
                        dayMaxScreenTemperature: 26.2,
                        nightMinScreenTemperature: 12.39,
                        dayUpperBoundMaxTemp: 28.27,
                        nightUpperBoundMinTemp: 16.38,
                        dayLowerBoundMaxTemp: 22.74,
                        nightLowerBoundMinTemp: 9.11,
                        dayMaxFeelsLikeTemp: 24.61,
                        nightMinFeelsLikeTemp: 13.25,
                        dayUpperBoundMaxFeelsLikeTemp: 26.92,
                        nightUpperBoundMinFeelsLikeTemp: 13.46,
                        dayLowerBoundMaxFeelsLikeTemp: 21.53,
                        nightLowerBoundMinFeelsLikeTemp: 8.01,
                        dayProbabilityOfPrecipitation: 1,
                        nightProbabilityOfPrecipitation: 1,
                        dayProbabilityOfSnow: 0,
                        nightProbabilityOfSnow: 0,
                        dayProbabilityOfHeavySnow: 0,
                        nightProbabilityOfHeavySnow: 0,
                        dayProbabilityOfRain: 1,
                        nightProbabilityOfRain: 1,
                        dayProbabilityOfHeavyRain: 0,
                        nightProbabilityOfHeavyRain: 0,
                        dayProbabilityOfHail: 0,
                        nightProbabilityOfHail: 0,
                        dayProbabilityOfSferics: 0,
                        nightProbabilityOfSferics: 0,
                    },
                ],
            },
        },
    ],
    parameters: [
        {
            daySignificantWeatherCode: {
                type: "Parameter",
                description: "Day Significant Weather Code",
                unit: {
                    label: "dimensionless",
                    symbol: {
                        value: "https://metoffice.apiconnect.ibmcloud.com/metoffice/production/",
                        type: "1",
                    },
                },
            },
            midnightRelativeHumidity: {
                type: "Parameter",
                description: "Relative Humidity at Local Midnight",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            nightProbabilityOfHeavyRain: {
                type: "Parameter",
                description: "Probability of Heavy Rain During The Night",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            midnight10MWindSpeed: {
                type: "Parameter",
                description: "10m Wind Speed at Local Midnight",
                unit: {
                    label: "metres per second",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "m/s",
                    },
                },
            },
            nightUpperBoundMinFeelsLikeTemp: {
                type: "Parameter",
                description:
                    "Upper Bound on Night Minimum Feels Like Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            nightUpperBoundMinTemp: {
                type: "Parameter",
                description:
                    "Upper Bound on Night Minimum Screen Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            midnightVisibility: {
                type: "Parameter",
                description: "Visibility at Local Midnight",
                unit: {
                    label: "metres",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "m",
                    },
                },
            },
            dayUpperBoundMaxFeelsLikeTemp: {
                type: "Parameter",
                description:
                    "Upper Bound on Day Maximum Feels Like Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            nightProbabilityOfRain: {
                type: "Parameter",
                description: "Probability of Rain During The Night",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            midday10MWindDirection: {
                type: "Parameter",
                description: "10m Wind Direction at Local Midday",
                unit: {
                    label: "degrees",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "deg",
                    },
                },
            },
            nightLowerBoundMinFeelsLikeTemp: {
                type: "Parameter",
                description:
                    "Lower Bound on Night Minimum Feels Like Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            nightProbabilityOfHail: {
                type: "Parameter",
                description: "Probability of Hail During The Night",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            middayMslp: {
                type: "Parameter",
                description: "Mean Sea Level Pressure at Local Midday",
                unit: {
                    label: "pascals",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Pa",
                    },
                },
            },
            dayProbabilityOfHeavySnow: {
                type: "Parameter",
                description: "Probability of Heavy Snow During The Day",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            nightProbabilityOfPrecipitation: {
                type: "Parameter",
                description: "Probability of Precipitation During The Night",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            dayProbabilityOfHail: {
                type: "Parameter",
                description: "Probability of Hail During The Day",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            dayProbabilityOfRain: {
                type: "Parameter",
                description: "Probability of Rain During The Day",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            midday10MWindSpeed: {
                type: "Parameter",
                description: "10m Wind Speed at Local Midday",
                unit: {
                    label: "metres per second",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "m/s",
                    },
                },
            },
            midday10MWindGust: {
                type: "Parameter",
                description: "10m Wind Gust Speed at Local Midday",
                unit: {
                    label: "metres per second",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "m/s",
                    },
                },
            },
            middayVisibility: {
                type: "Parameter",
                description: "Visibility at Local Midday",
                unit: {
                    label: "metres",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "m",
                    },
                },
            },
            midnight10MWindGust: {
                type: "Parameter",
                description: "10m Wind Gust Speed at Local Midnight",
                unit: {
                    label: "metres per second",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "m/s",
                    },
                },
            },
            midnightMslp: {
                type: "Parameter",
                description: "Mean Sea Level Pressure at Local Midnight",
                unit: {
                    label: "pascals",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Pa",
                    },
                },
            },
            dayProbabilityOfSferics: {
                type: "Parameter",
                description: "Probability of Sferics During The Day",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            nightSignificantWeatherCode: {
                type: "Parameter",
                description: "Night Significant Weather Code",
                unit: {
                    label: "dimensionless",
                    symbol: {
                        value: "https://metoffice.apiconnect.ibmcloud.com/metoffice/production/",
                        type: "1",
                    },
                },
            },
            dayProbabilityOfPrecipitation: {
                type: "Parameter",
                description: "Probability of Precipitation During The Day",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            dayProbabilityOfHeavyRain: {
                type: "Parameter",
                description: "Probability of Heavy Rain During The Day",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            dayMaxScreenTemperature: {
                type: "Parameter",
                description: "Day Maximum Screen Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            nightMinScreenTemperature: {
                type: "Parameter",
                description: "Night Minimum Screen Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            midnight10MWindDirection: {
                type: "Parameter",
                description: "10m Wind Direction at Local Midnight",
                unit: {
                    label: "degrees",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "deg",
                    },
                },
            },
            maxUvIndex: {
                type: "Parameter",
                description: "Day Maximum UV Index",
                unit: {
                    label: "dimensionless",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "1",
                    },
                },
            },
            dayProbabilityOfSnow: {
                type: "Parameter",
                description: "Probability of Snow During The Day",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            nightProbabilityOfSnow: {
                type: "Parameter",
                description: "Probability of Snow During The Night",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            dayLowerBoundMaxTemp: {
                type: "Parameter",
                description:
                    "Lower Bound on Day Maximum Screen Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            nightProbabilityOfHeavySnow: {
                type: "Parameter",
                description: "Probability of Heavy Snow During The Night",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            dayLowerBoundMaxFeelsLikeTemp: {
                type: "Parameter",
                description:
                    "Lower Bound on Day Maximum Feels Like Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            dayUpperBoundMaxTemp: {
                type: "Parameter",
                description:
                    "Upper Bound on Day Maximum Screen Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            dayMaxFeelsLikeTemp: {
                type: "Parameter",
                description: "Day Maximum Feels Like Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            middayRelativeHumidity: {
                type: "Parameter",
                description: "Relative Humidity at Local Midday",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
            nightLowerBoundMinTemp: {
                type: "Parameter",
                description:
                    "Lower Bound on Night Minimum Screen Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            nightMinFeelsLikeTemp: {
                type: "Parameter",
                description: "Night Minimum Feels Like Air Temperature",
                unit: {
                    label: "degrees Celsius",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "Cel",
                    },
                },
            },
            nightProbabilityOfSferics: {
                type: "Parameter",
                description: "Probability of Sferics During The Night",
                unit: {
                    label: "percentage",
                    symbol: {
                        value: "http://www.opengis.net/def/uom/UCUM/",
                        type: "%",
                    },
                },
            },
        },
    ],
    location: "Cinderford",
    days: [
        {
            time: "2022-08-02T00:00Z",
            midnight10MWindSpeed: 6.22,
            midnight10MWindDirection: 229,
            midnight10MWindGust: 12.86,
            midnightVisibility: 14734,
            midnightRelativeHumidity: 89.55,
            midnightMslp: 101240,
            nightSignificantWeatherCode: 7,
            nightMinScreenTemperature: 17.76,
            nightUpperBoundMinTemp: 18.26,
            nightLowerBoundMinTemp: 16.26,
            nightMinFeelsLikeTemp: 16.58,
            nightUpperBoundMinFeelsLikeTemp: 16.58,
            nightLowerBoundMinFeelsLikeTemp: 14.69,
            nightProbabilityOfPrecipitation: 10,
            nightProbabilityOfSnow: 0,
            nightProbabilityOfHeavySnow: 0,
            nightProbabilityOfRain: 10,
            nightProbabilityOfHeavyRain: 2,
            nightProbabilityOfHail: 0,
            nightProbabilityOfSferics: 0,
        },
        {
            time: "2022-08-03T00:00Z",
            midday10MWindSpeed: 6.07,
            midnight10MWindSpeed: 2.8,
            midday10MWindDirection: 236,
            midnight10MWindDirection: 271,
            midday10MWindGust: 9.77,
            midnight10MWindGust: 8.08,
            middayVisibility: 22594,
            midnightVisibility: 25202,
            middayRelativeHumidity: 72.83,
            midnightRelativeHumidity: 80.61,
            middayMslp: 101280,
            midnightMslp: 101380,
            maxUvIndex: 1,
            daySignificantWeatherCode: 7,
            nightSignificantWeatherCode: 0,
            dayMaxScreenTemperature: 22.9,
            nightMinScreenTemperature: 13.24,
            dayUpperBoundMaxTemp: 23.94,
            nightUpperBoundMinTemp: 14.01,
            dayLowerBoundMaxTemp: 21,
            nightLowerBoundMinTemp: 11,
            dayMaxFeelsLikeTemp: 20.47,
            nightMinFeelsLikeTemp: 12.65,
            dayUpperBoundMaxFeelsLikeTemp: 20.94,
            nightUpperBoundMinFeelsLikeTemp: 13.04,
            dayLowerBoundMaxFeelsLikeTemp: 18.19,
            nightLowerBoundMinFeelsLikeTemp: 10.14,
            dayProbabilityOfPrecipitation: 3,
            nightProbabilityOfPrecipitation: 0,
            dayProbabilityOfSnow: 0,
            nightProbabilityOfSnow: 0,
            dayProbabilityOfHeavySnow: 0,
            nightProbabilityOfHeavySnow: 0,
            dayProbabilityOfRain: 3,
            nightProbabilityOfRain: 0,
            dayProbabilityOfHeavyRain: 0,
            nightProbabilityOfHeavyRain: 0,
            dayProbabilityOfHail: 0,
            nightProbabilityOfHail: 0,
            dayProbabilityOfSferics: 0,
            nightProbabilityOfSferics: 0,
        },
        {
            time: "2022-08-04T00:00Z",
            midday10MWindSpeed: 3.75,
            midnight10MWindSpeed: 3.59,
            midday10MWindDirection: 313,
            midnight10MWindDirection: 329,
            midday10MWindGust: 6.96,
            midnight10MWindGust: 7.78,
            middayVisibility: 43902,
            midnightVisibility: 35064,
            middayRelativeHumidity: 39.24,
            midnightRelativeHumidity: 63.57,
            middayMslp: 101690,
            midnightMslp: 102128,
            maxUvIndex: 6,
            daySignificantWeatherCode: 7,
            nightSignificantWeatherCode: 0,
            dayMaxScreenTemperature: 21.12,
            nightMinScreenTemperature: 10.26,
            dayUpperBoundMaxTemp: 21.91,
            nightUpperBoundMinTemp: 11,
            dayLowerBoundMaxTemp: 18.77,
            nightLowerBoundMinTemp: 7.02,
            dayMaxFeelsLikeTemp: 18.06,
            nightMinFeelsLikeTemp: 8.79,
            dayUpperBoundMaxFeelsLikeTemp: 19.28,
            nightUpperBoundMinFeelsLikeTemp: 9.2,
            dayLowerBoundMaxFeelsLikeTemp: 16.57,
            nightLowerBoundMinFeelsLikeTemp: 7.53,
            dayProbabilityOfPrecipitation: 4,
            nightProbabilityOfPrecipitation: 0,
            dayProbabilityOfSnow: 0,
            nightProbabilityOfSnow: 0,
            dayProbabilityOfHeavySnow: 0,
            nightProbabilityOfHeavySnow: 0,
            dayProbabilityOfRain: 4,
            nightProbabilityOfRain: 0,
            dayProbabilityOfHeavyRain: 0,
            nightProbabilityOfHeavyRain: 0,
            dayProbabilityOfHail: 0,
            nightProbabilityOfHail: 0,
            dayProbabilityOfSferics: 0,
            nightProbabilityOfSferics: 0,
        },
        {
            time: "2022-08-05T00:00Z",
            midday10MWindSpeed: 4.51,
            midnight10MWindSpeed: 2.67,
            midday10MWindDirection: 321,
            midnight10MWindDirection: 341,
            midday10MWindGust: 8.68,
            midnight10MWindGust: 5.33,
            middayVisibility: 43477,
            midnightVisibility: 31823,
            middayRelativeHumidity: 38.44,
            midnightRelativeHumidity: 75.94,
            middayMslp: 102427,
            midnightMslp: 102864,
            maxUvIndex: 6,
            daySignificantWeatherCode: 3,
            nightSignificantWeatherCode: 0,
            dayMaxScreenTemperature: 19.66,
            nightMinScreenTemperature: 7.62,
            dayUpperBoundMaxTemp: 21.21,
            nightUpperBoundMinTemp: 10.17,
            dayLowerBoundMaxTemp: 18.1,
            nightLowerBoundMinTemp: 4.82,
            dayMaxFeelsLikeTemp: 16.21,
            nightMinFeelsLikeTemp: 7.42,
            dayUpperBoundMaxFeelsLikeTemp: 18.67,
            nightUpperBoundMinFeelsLikeTemp: 9.07,
            dayLowerBoundMaxFeelsLikeTemp: 16.1,
            nightLowerBoundMinFeelsLikeTemp: 2.32,
            dayProbabilityOfPrecipitation: 4,
            nightProbabilityOfPrecipitation: 0,
            dayProbabilityOfSnow: 0,
            nightProbabilityOfSnow: 0,
            dayProbabilityOfHeavySnow: 0,
            nightProbabilityOfHeavySnow: 0,
            dayProbabilityOfRain: 4,
            nightProbabilityOfRain: 0,
            dayProbabilityOfHeavyRain: 0,
            nightProbabilityOfHeavyRain: 0,
            dayProbabilityOfHail: 0,
            nightProbabilityOfHail: 0,
            dayProbabilityOfSferics: 0,
            nightProbabilityOfSferics: 0,
        },
        {
            time: "2022-08-06T00:00Z",
            midday10MWindSpeed: 2.3,
            midnight10MWindSpeed: 3.03,
            midday10MWindDirection: 359,
            midnight10MWindDirection: 359,
            midday10MWindGust: 6.38,
            midnight10MWindGust: 5.34,
            middayVisibility: 35834,
            midnightVisibility: 31577,
            middayRelativeHumidity: 41.87,
            midnightRelativeHumidity: 73.84,
            middayMslp: 102992,
            midnightMslp: 102932,
            maxUvIndex: 6,
            daySignificantWeatherCode: 3,
            nightSignificantWeatherCode: 0,
            dayMaxScreenTemperature: 20.4,
            nightMinScreenTemperature: 9.55,
            dayUpperBoundMaxTemp: 21.42,
            nightUpperBoundMinTemp: 11.52,
            dayLowerBoundMaxTemp: 18.26,
            nightLowerBoundMinTemp: 6.5,
            dayMaxFeelsLikeTemp: 18.54,
            nightMinFeelsLikeTemp: 9.36,
            dayUpperBoundMaxFeelsLikeTemp: 19.79,
            nightUpperBoundMinFeelsLikeTemp: 9.39,
            dayLowerBoundMaxFeelsLikeTemp: 16.68,
            nightLowerBoundMinFeelsLikeTemp: 5.17,
            dayProbabilityOfPrecipitation: 4,
            nightProbabilityOfPrecipitation: 1,
            dayProbabilityOfSnow: 0,
            nightProbabilityOfSnow: 0,
            dayProbabilityOfHeavySnow: 0,
            nightProbabilityOfHeavySnow: 0,
            dayProbabilityOfRain: 4,
            nightProbabilityOfRain: 1,
            dayProbabilityOfHeavyRain: 0,
            nightProbabilityOfHeavyRain: 0,
            dayProbabilityOfHail: 0,
            nightProbabilityOfHail: 0,
            dayProbabilityOfSferics: 0,
            nightProbabilityOfSferics: 0,
        },
        {
            time: "2022-08-07T00:00Z",
            midday10MWindSpeed: 1.83,
            midnight10MWindSpeed: 3.54,
            midday10MWindDirection: 22,
            midnight10MWindDirection: 12,
            midday10MWindGust: 6.1,
            midnight10MWindGust: 5.97,
            middayVisibility: 32831,
            midnightVisibility: 31256,
            middayRelativeHumidity: 44.58,
            midnightRelativeHumidity: 74.66,
            middayMslp: 102831,
            midnightMslp: 102702,
            maxUvIndex: 7,
            daySignificantWeatherCode: 3,
            nightSignificantWeatherCode: 0,
            dayMaxScreenTemperature: 22.64,
            nightMinScreenTemperature: 10.59,
            dayUpperBoundMaxTemp: 24.06,
            nightUpperBoundMinTemp: 11.96,
            dayLowerBoundMaxTemp: 20.51,
            nightLowerBoundMinTemp: 7.97,
            dayMaxFeelsLikeTemp: 20.96,
            nightMinFeelsLikeTemp: 10.57,
            dayUpperBoundMaxFeelsLikeTemp: 23.15,
            nightUpperBoundMinFeelsLikeTemp: 11.16,
            dayLowerBoundMaxFeelsLikeTemp: 18.95,
            nightLowerBoundMinFeelsLikeTemp: 6.27,
            dayProbabilityOfPrecipitation: 3,
            nightProbabilityOfPrecipitation: 0,
            dayProbabilityOfSnow: 0,
            nightProbabilityOfSnow: 0,
            dayProbabilityOfHeavySnow: 0,
            nightProbabilityOfHeavySnow: 0,
            dayProbabilityOfRain: 3,
            nightProbabilityOfRain: 0,
            dayProbabilityOfHeavyRain: 0,
            nightProbabilityOfHeavyRain: 0,
            dayProbabilityOfHail: 0,
            nightProbabilityOfHail: 0,
            dayProbabilityOfSferics: 0,
            nightProbabilityOfSferics: 0,
        },
        {
            time: "2022-08-08T00:00Z",
            midday10MWindSpeed: 2.22,
            midnight10MWindSpeed: 3.76,
            midday10MWindDirection: 107,
            midnight10MWindDirection: 24,
            midday10MWindGust: 6.91,
            midnight10MWindGust: 6.05,
            middayVisibility: 34903,
            midnightVisibility: 30652,
            middayRelativeHumidity: 42.62,
            midnightRelativeHumidity: 72.11,
            middayMslp: 102612,
            midnightMslp: 102552,
            maxUvIndex: 7,
            daySignificantWeatherCode: 1,
            nightSignificantWeatherCode: 0,
            dayMaxScreenTemperature: 24.63,
            nightMinScreenTemperature: 11.61,
            dayUpperBoundMaxTemp: 26.72,
            nightUpperBoundMinTemp: 13.46,
            dayLowerBoundMaxTemp: 22.61,
            nightLowerBoundMinTemp: 8.6,
            dayMaxFeelsLikeTemp: 23.38,
            nightMinFeelsLikeTemp: 11.77,
            dayUpperBoundMaxFeelsLikeTemp: 25.25,
            nightUpperBoundMinFeelsLikeTemp: 11.89,
            dayLowerBoundMaxFeelsLikeTemp: 20.55,
            nightLowerBoundMinFeelsLikeTemp: 7.93,
            dayProbabilityOfPrecipitation: 0,
            nightProbabilityOfPrecipitation: 0,
            dayProbabilityOfSnow: 0,
            nightProbabilityOfSnow: 0,
            dayProbabilityOfHeavySnow: 0,
            nightProbabilityOfHeavySnow: 0,
            dayProbabilityOfRain: 0,
            nightProbabilityOfRain: 0,
            dayProbabilityOfHeavyRain: 0,
            nightProbabilityOfHeavyRain: 0,
            dayProbabilityOfHail: 0,
            nightProbabilityOfHail: 0,
            dayProbabilityOfSferics: 0,
            nightProbabilityOfSferics: 0,
        },
        {
            time: "2022-08-09T00:00Z",
            midday10MWindSpeed: 2.37,
            midnight10MWindSpeed: 3.44,
            midday10MWindDirection: 130,
            midnight10MWindDirection: 37,
            midday10MWindGust: 6.96,
            midnight10MWindGust: 5.47,
            middayVisibility: 34489,
            midnightVisibility: 29094,
            middayRelativeHumidity: 42.39,
            midnightRelativeHumidity: 77.72,
            middayMslp: 102484,
            midnightMslp: 102356,
            maxUvIndex: 6,
            daySignificantWeatherCode: 1,
            nightSignificantWeatherCode: 0,
            dayMaxScreenTemperature: 26.2,
            nightMinScreenTemperature: 12.39,
            dayUpperBoundMaxTemp: 28.27,
            nightUpperBoundMinTemp: 16.38,
            dayLowerBoundMaxTemp: 22.74,
            nightLowerBoundMinTemp: 9.11,
            dayMaxFeelsLikeTemp: 24.61,
            nightMinFeelsLikeTemp: 13.25,
            dayUpperBoundMaxFeelsLikeTemp: 26.92,
            nightUpperBoundMinFeelsLikeTemp: 13.46,
            dayLowerBoundMaxFeelsLikeTemp: 21.53,
            nightLowerBoundMinFeelsLikeTemp: 8.01,
            dayProbabilityOfPrecipitation: 1,
            nightProbabilityOfPrecipitation: 1,
            dayProbabilityOfSnow: 0,
            nightProbabilityOfSnow: 0,
            dayProbabilityOfHeavySnow: 0,
            nightProbabilityOfHeavySnow: 0,
            dayProbabilityOfRain: 1,
            nightProbabilityOfRain: 1,
            dayProbabilityOfHeavyRain: 0,
            nightProbabilityOfHeavyRain: 0,
            dayProbabilityOfHail: 0,
            nightProbabilityOfHail: 0,
            dayProbabilityOfSferics: 0,
            nightProbabilityOfSferics: 0,
        },
    ],
};

export const MOCK_BBC_NEWS_RESPONSE = [
    {
        title: "Archie's family seek permission for hospice move",
        link: "https://bbc.co.uk/news/uk-england-essex-62418257",
        img: "https://ichef.bbci.co.uk/news/490/cpsprodpb/11809/production/_126098617_hi075971431.jpg",
        date: "04/08/2022",
        site: "uk-england-essex-62418257",
    },
    {
        title: "UK interest rates see biggest rise in 27 years",
        link: "https://bbc.co.uk/news/business-62405037",
        img: "https://ichef.bbci.co.uk/news/720/cpsprodpb/4767/production/_126197281_gettyimages-152838792.jpg",
        date: "04/08/2022",
        site: "business-62405037",
    },
    {
        title: "Fourth murder arrest over missing student nurse",
        link: "https://bbc.co.uk/news/uk-england-london-62421788",
        img: "https://ichef.bbci.co.uk/news/720/cpsprodpb/107C0/production/_126202576_owami-davies.jpg",
        date: "04/08/2022",
        site: "uk-england-london-62421788",
    },
    {
        title: "Stabbed girl, 9, died of chest wound - inquest",
        link: "https://bbc.co.uk/news/uk-england-lincolnshire-62425278",
        img: "https://ichef.bbci.co.uk/news/720/cpsprodpb/147B2/production/_126109838_mediaitem126109566.jpg",
        date: "04/08/2022",
        site: "uk-england-lincolnshire-62425278",
    },
    {
        title: "'Seeing my house like this just makes me sad'",
        link: "https://bbc.co.uk/news/uk-england-london-62422769",
        img: "https://ichef.bbci.co.uk/news/720/cpsprodpb/98BB/production/_126199093_p0cr1k8q.jpg",
        date: "04/08/2022",
        site: "uk-england-london-62422769",
    },
];

export const MOCK_GAMING_NEWS_RESPONSE = [
    {
        title: "Fromsoft CEO Hidetaka Miyazaki to receive the top gong from Japan's industry body",
        link: "https://www.pcgamer.com/fromsoft-ceo-hidetaka-miyazaki-to-receive-the-top-gong-from-japans-industry-body/",
        img: "https://cdn.mos.cms.futurecdn.net/xNdteGXNmaomL78qRJoe5Y.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "Steam Deck preorders are finally available in parts of Asia",
        link: "https://www.pcgamer.com/steam-deck-preorders-are-finally-available-in-parts-of-asia/",
        img: "https://cdn.mos.cms.futurecdn.net/pasVmcfXubSkdDq2QD89cX.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "Koch Media got so sick of the jokes it's changed its name",
        link: "https://www.pcgamer.com/koch-media-got-so-sick-of-the-jokes-its-changed-its-name/",
        img: "https://cdn.mos.cms.futurecdn.net/PhWz3PVQBcxEnkjPt4M4bC.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "The Future Games Show is coming to Gamescom 2022",
        link: "https://www.pcgamer.com/the-future-games-show-is-coming-to-gamescom-2022/",
        img: "https://cdn.mos.cms.futurecdn.net/w5yNw3byKstMs3rNwQJbzU.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "A CPU world record has been broken by dousing a $6,000+ AMD chip in liquid nitrogen",
        link: "https://www.pcgamer.com/a-cpu-world-record-has-been-broken-by-dousing-a-dollar6000-amd-chip-in-liquid-nitrogen/",
        img: "https://cdn.mos.cms.futurecdn.net/6E9ayVshhvaJCyCFzD3RL4.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "This Doom modder is sending Max Payne to Mars in 'Doom Payne'",
        link: "https://www.pcgamer.com/this-doom-modder-is-sending-max-payne-to-mars-in-doom-payne/",
        img: "https://cdn.mos.cms.futurecdn.net/SqygnQKrttVmVqhJdEThHR.jpeg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "You've got until 2025 to upgrade to Wi-Fi 6 before it's yesterday's news",
        link: "https://www.pcgamer.com/wi-fi-7-intel-double-speeds/",
        img: "https://cdn.mos.cms.futurecdn.net/KT2DLTE6eeNnRmGfU9sS6d.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "Tencent makes megabucks offer to buy majority stake in Ubisoft",
        link: "https://www.pcgamer.com/tencent-makes-megabucks-offer-to-buy-majority-stake-in-ubisoft/",
        img: "https://cdn.mos.cms.futurecdn.net/kVj2VgatZoWMErQmWiFrEg.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "Intel's Arc GPU launch appears to have gone from headache to migraine",
        link: "https://www.pcgamer.com/intels-arc-gpu-launch-appears-to-have-gone-from-headache-to-migraine/",
        img: "https://cdn.mos.cms.futurecdn.net/eB5h5HpHMdNZGEufuvgKwU.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
    {
        title: "Blizzard probably isn't going to charge you $45 for an Overwatch 2 skin",
        link: "https://www.pcgamer.com/blizzard-probably-isnt-going-to-charge-you-dollar45-for-an-overwatch-2-skin/",
        img: "https://cdn.mos.cms.futurecdn.net/YBndYmtNYSRnCHgVbZuHjk.jpg",
        date: "04/08/2022",
        site: "www.pcgamer.com",
    },
];

export const MOCK_NASA_NEWS_RESPONSE = {
    copyright: "Joan Josep Isach Cogollos",
    date: "2022-08-04",
    explanation:
        'In 1716, English astronomer Edmond Halley noted, "This is but a little Patch, but it shows itself to the naked Eye, when the Sky is serene and the Moon absent." Of course, M13 is now less modestly recognized as the Great Globular Cluster in Hercules, one of the brightest globular star clusters in the northern sky. Sharp telescopic views like this one reveal the spectacular cluster\'s hundreds of thousands of stars. At a distance of 25,000 light-years, the cluster stars crowd into a region 150 light-years in diameter. Approaching the cluster core upwards of 100 stars could be contained in a cube just 3 light-years on a side. For comparison, the closest star to the Sun is over 4 light-years away. The remarkable range of brightness recorded in this image follows stars into the dense cluster core. Distant background galaxies in the medium-wide field of view include NGC 6207 at the upper left.',
    hdurl: "https://apod.nasa.gov/apod/image/2208/M13_final2_sinfirma.jpg",
    media_type: "image",
    service_version: "v1",
    title: "M13: The Great Globular Cluster in Hercules",
    url: "https://apod.nasa.gov/apod/image/2208/M13_final2_sinfirma1024.jpg",
};

export const MOCK_NEWS_RESPONSE: NewsResponse = {
    gaming: MOCK_GAMING_NEWS_RESPONSE,
    news: MOCK_BBC_NEWS_RESPONSE,
    nasa: MOCK_NASA_NEWS_RESPONSE,
};
